### ISSUE TITLE
Does it have to be an upgrade?

### ISSUE THREAD

**Issue by denogio** [jules-ch/Ubuntu20-Setup-XPS13#1]
Can this be don on a fresh 20.04 install on my XPS 9300?

**Comment by jules-ch** [comment]
No it doesn't have to be an upgrade. A fresh install might already install the dell oem repository, but you can safely run this script on a fresh ubuntu 20.04 install. :)

**Comment by denogio** [comment]
Cool thank you. That's what i've already done, but i have some resumption issues - that is why i asked. Do you experience issues after resumption. My XPS 9300 becomes so much slower and sluggish after resumption. A fresh restart and the XPS is back to normal, but that's not really what i expect from a $2200 laptop.
