### ISSUE TITLE
Question about XPS13 9300 Ubuntu 20.04

### ISSUE THREAD

**Issue by fggarcia** [jules-ch/Ubuntu20-Setup-XPS13#2]
hi @jules-ch @dhpowrhost

Sorry for ask you here.

In your installation, custom charge threshold (advance settings for battery) works on ubuntu 20.04??

**Comment by jules-ch** [comment]
Hey for the xps 13 those settings are set in the BIOS it can't be set with a simple bash script

**Comment by fggarcia** [comment]
Hi @jules-ch . Yes I set it in bios. But when I use the laptop , the battery doesn't stop charge when reach the limit.
I want to know if this is a hardware issue or not working in la linux

**Comment by jules-ch** [comment]
I had no problem setting such threshold, charge is stopping at the desired charge on my laptop.
I'd say check with Dell support if you can have an answer on their end.
