### ISSUE TITLE
Any issues with performance? [QUESTION]

### ISSUE THREAD

**Issue by dtiziani** [jules-ch/Ubuntu20-Setup-XPS13#5]
I'm running Ubuntu 20.04 here, checked your script. 
Having a lot of performance issues with that, it's kinda ridiculous, so I thought: why not ask?

Been through a lot of suggestions, latest version of GRUB parameters I could make it improve a little bit was: 
`i915.enable_psr=0 mem_sleep_default=deep i915.enable_guc=2 i915.enable_dp_mst=0 quiet splash`

Did you face any issues with performance? (High RAM usage, X looks slugish with just a few apps opened).

**Comment by denogio** [comment]
My performance issues are mainly on battery. I have the 9300 with a 4k touch, and as long as the battery is above 50% everything is fine, but below everything is sluggish.

Tried a livecd with endeavourOS with low battery and everything was snappy. Been running ubuntu all my techlife, but i consider trying endeavourOS.

**Comment by jules-ch** [comment]
I've got a FullHD touch screen & no performance issue so far. :/
